#!/usr/bin/env python3
"""Build prioritized museum prefix backlog for TypeSpecimenMetadata updates."""

from __future__ import annotations

import csv
from pathlib import Path

OUT = Path(__file__).resolve().parents[1] / "data" / "review" / "museum_prefix_priority_backlog.csv"

# Curated backlog: priority 1 = highest
ROWS = [
    # --- P1: completely absent, ≥10 species, clear institution ---
    dict(
        priority=1,
        impact="completely_excluded",
        prefix="ZMUC",
        species_count=19,
        suggested_full_name="Zoological Museum, University of Copenhagen",
        city_country="Copenhagen, Denmark",
        fix_type="add_abbreviation",
        related_metadata="",
        in_app_via="",
        action="Add ZMUC row (NHRM-style; vouchers use ZMUC, not in metadata).",
    ),
    dict(
        priority=1,
        impact="completely_excluded",
        prefix="MTD",
        species_count=18,
        suggested_full_name="Senckenberg Museum für Tierkunde Dresden",
        city_country="Dresden, Germany",
        fix_type="add_abbreviation",
        related_metadata="SMF (Senckenberg Frankfurt)",
        in_app_via="",
        action="Add MTD row; Dresden collection distinct from Frankfurt SMF.",
    ),
    dict(
        priority=1,
        impact="completely_excluded",
        prefix="SAF",
        species_count=26,
        suggested_full_name="Sichuan Academy of Forestry",
        city_country="Sichuan, China",
        fix_type="add_abbreviation",
        related_metadata="",
        in_app_via="",
        action="Add SAF row; many Ochotona vouchers (often with SCNU numbers).",
    ),
    dict(
        priority=1,
        impact="completely_excluded",
        prefix="BIZ",
        species_count=10,
        suggested_full_name="Institute of Zoology (Beijing) / Beijing specimen catalog prefix BIZ",
        city_country="Beijing, China",
        fix_type="add_alias",
        related_metadata="IOZCAS (zero matches)",
        in_app_via="",
        action="Add BIZ alias; likely overlaps IOZCAS collection (verify with IOZ).",
    ),
    dict(
        priority=1,
        impact="needs_review",
        prefix="MN",
        species_count=53,
        suggested_full_name="Ambiguous — verify per voucher (not one museum?)",
        city_country="",
        fix_type="manual_review",
        related_metadata="MNCN; MNHN; MNZ",
        in_app_via="",
        action="Do not bulk-add MN. Vouchers mix MNCN refs and bare MN numbers; MN 78680 cited as AMNH in literature. Split by voucher before adding.",
    ),
    # --- P2: completely absent, 5–9 species OR clear alias to existing row ---
    dict(
        priority=2,
        impact="completely_excluded",
        prefix="DNSM",
        species_count=8,
        suggested_full_name="Durban Natural Science Museum",
        city_country="Durban, South Africa",
        fix_type="add_alias",
        related_metadata="DM",
        in_app_via="",
        action="Add DNSM alias for DM (NRM-style; vouchers say DNSM not DM).",
    ),
    dict(
        priority=2,
        impact="completely_excluded",
        prefix="CNMA",
        species_count=7,
        suggested_full_name="Colección Nacional de Mamíferos (UNAM)",
        city_country="Mexico City, Mexico",
        fix_type="add_alias",
        related_metadata="IBUNAM (CNMA)",
        in_app_via="",
        action="Add CNMA row pointing to same institution as IBUNAM (CNMA).",
    ),
    dict(
        priority=2,
        impact="completely_excluded",
        prefix="UCLA",
        species_count=8,
        suggested_full_name="UCLA Mammalogy Collection / Dickey Collection",
        city_country="Los Angeles, United States of America",
        fix_type="add_abbreviation",
        related_metadata="",
        in_app_via="",
        action="Add UCLA row for mammal vouchers (incl. Dickey collection numbers).",
    ),
    dict(
        priority=2,
        impact="completely_excluded",
        prefix="CSIRO",
        species_count=6,
        suggested_full_name="CSIRO Australian National Wildlife Collection",
        city_country="Canberra, Australia",
        fix_type="add_abbreviation",
        related_metadata="ANWC",
        in_app_via="",
        action="Add CSIRO or map to ANWC if same collection (verify).",
    ),
    dict(
        priority=2,
        impact="completely_excluded",
        prefix="TNRC",
        species_count=5,
        suggested_full_name="Centre for Thai National Reference Collections",
        city_country="Bangkok, Thailand",
        fix_type="add_alias",
        related_metadata="CTNRC (zero matches)",
        in_app_via="",
        action="Add TNRC alias; metadata has CTNRC but vouchers use TNRC.",
    ),
    dict(
        priority=2,
        impact="completely_excluded",
        prefix="MF",
        species_count=6,
        suggested_full_name="Museo di Storia Naturale dell'Università di Firenze (verify)",
        city_country="Florence, Italy",
        fix_type="add_abbreviation",
        related_metadata="",
        in_app_via="",
        action="Confirm MF = Florence natural history museum; includes Elephas lectotype MF 734.",
    ),
    dict(
        priority=2,
        impact="completely_excluded",
        prefix="FMSM",
        species_count=6,
        suggested_full_name="Fukushima Museum (verify)",
        city_country="Japan",
        fix_type="add_abbreviation",
        related_metadata="",
        in_app_via="",
        action="Verify institution for Japanese/Indonesian rodent vouchers.",
    ),
    dict(
        priority=2,
        impact="completely_excluded",
        prefix="AHUB",
        species_count=6,
        suggested_full_name="Anhui University / Anhui Normal University (verify)",
        city_country="Anhui, China",
        fix_type="add_abbreviation",
        related_metadata="",
        in_app_via="",
        action="Chinese small-mammal types; confirm holding institution.",
    ),
    dict(
        priority=2,
        impact="completely_excluded",
        prefix="IES",
        species_count=5,
        suggested_full_name="Institute of Ecology and Systematics, Cuba (verify)",
        city_country="Cuba",
        fix_type="add_abbreviation",
        related_metadata="",
        in_app_via="",
        action="Capromys / hutia types; verify IES expansion.",
    ),
    dict(
        priority=2,
        impact="completely_excluded",
        prefix="ZMF",
        species_count=5,
        suggested_full_name="Zoological Museum Frankfurt (verify)",
        city_country="Frankfurt, Germany",
        fix_type="add_abbreviation",
        related_metadata="SMF",
        in_app_via="",
        action="Distinguish from SMF Senckenberg if separate catalog.",
    ),
    # --- P3: filter/alias — already matched via shorter code ---
    dict(
        priority=3,
        impact="hidden_alias",
        prefix="BMNH",
        species_count=19,
        suggested_full_name="Natural History Museum, London",
        city_country="London, United Kingdom",
        fix_type="add_alias",
        related_metadata="BM",
        in_app_via="BM",
        action="Add BMNH alias so museum filter matches voucher prefix (already on map as BM).",
    ),
    dict(
        priority=3,
        impact="hidden_alias",
        prefix="NMPR",
        species_count=15,
        suggested_full_name="National Museum (Natural History), Prague",
        city_country="Prague, Czech Republic",
        fix_type="add_alias",
        related_metadata="NMP",
        in_app_via="NMP",
        action="Add NMPR alias; vouchers often NMPr (case-insensitive match to NMP today).",
    ),
    dict(
        priority=3,
        impact="hidden_alias",
        prefix="MACN-MA",
        species_count=17,
        suggested_full_name="Museo Argentino de Ciencias Naturales Bernardino Rivadavia",
        city_country="Buenos Aires, Argentina",
        fix_type="add_alias",
        related_metadata="MACN",
        in_app_via="MACN",
        action="Add MACN-MA alias; vouchers use MACN-Ma.",
    ),
    dict(
        priority=3,
        impact="hidden_alias",
        prefix="NSMT-M",
        species_count=15,
        suggested_full_name="National Museum of Nature and Science, Tokyo",
        city_country="Tokyo, Japan",
        fix_type="add_alias",
        related_metadata="NSMT",
        in_app_via="NSMT",
        action="Add NSMT-M alias for mammal sub-collection prefix.",
    ),
    dict(
        priority=3,
        impact="hidden_alias",
        prefix="OUM",
        species_count=2,
        suggested_full_name="Oxford University Museum of Natural History",
        city_country="Oxford, United Kingdom",
        fix_type="add_alias",
        related_metadata="OUMNH (zero matches)",
        in_app_via="OUMNH via longer match? verify",
        action="Add OUM alias; metadata OUMNH never matches OUM vouchers.",
    ),
    dict(
        priority=3,
        impact="hidden_alias",
        prefix="NMNZ",
        species_count=3,
        suggested_full_name="Museum of New Zealand Te Papa Tongarewa",
        city_country="Wellington, New Zealand",
        fix_type="add_alias",
        related_metadata="MNZ (zero matches)",
        in_app_via="",
        action="Add NMNZ alias; metadata MNZ does not match NMNZ prefix.",
    ),
    dict(
        priority=3,
        impact="hidden_alias",
        prefix="DMNH",
        species_count=4,
        suggested_full_name="Durban Natural Science Museum (verify not Denver)",
        city_country="Durban, South Africa",
        fix_type="add_alias",
        related_metadata="DM",
        in_app_via="DM",
        action="Clarify DMNH vs DNSM vs DM — may be same Durban museum.",
    ),
    dict(
        priority=3,
        impact="hidden_alias",
        prefix="MNHNU",
        species_count=4,
        suggested_full_name="Museum National d'Histoire Naturelle",
        city_country="Paris, France",
        fix_type="add_alias",
        related_metadata="MNHN",
        in_app_via="MNHN",
        action="Add MNHNU alias for Paris mammal catalog variant.",
    ),
    dict(
        priority=3,
        impact="hidden_alias",
        prefix="CML",
        species_count=9,
        suggested_full_name="Colección Mamíferos Lillo",
        city_country="Tucumán, Argentina",
        fix_type="add_alias",
        related_metadata="CML  (trailing space in metadata)",
        in_app_via="CML ",
        action="Fix metadata typo (trailing space) and add CML alias row.",
    ),
    # --- P4: metadata exists, zero matches — enable via alias ---
    dict(
        priority=4,
        impact="zero_match_metadata",
        prefix="IOZCAS",
        species_count=0,
        suggested_full_name="Institute of Zoology, Chinese Academy of Sciences",
        city_country="Beijing, China",
        fix_type="add_alias",
        related_metadata="IOZCAS; BIZ vouchers",
        in_app_via="",
        action="Add BIZ/IZCAS variants; IOZCAS listed but never matched.",
    ),
    dict(
        priority=4,
        impact="zero_match_metadata",
        prefix="CUMV",
        species_count=0,
        suggested_full_name="Cornell University Museum of Vertebrates",
        city_country="Ithaca, United States of America",
        fix_type="investigate",
        related_metadata="CUMV",
        in_app_via="",
        action="In metadata, no MDD vouchers — no action unless vouchers added.",
    ),
    dict(
        priority=4,
        impact="zero_match_metadata",
        prefix="NMSL",
        species_count=0,
        suggested_full_name="National Museum of Sri Lanka, Colombo",
        city_country="Colombo, Sri Lanka",
        fix_type="investigate",
        related_metadata="NMSL",
        in_app_via="",
        action="In metadata, no matching vouchers in MDD v2.4.",
    ),
    dict(
        priority=4,
        impact="zero_match_metadata",
        prefix="OUMNH",
        species_count=0,
        suggested_full_name="Oxford University Museum of Natural History",
        city_country="Oxford, United Kingdom",
        fix_type="add_alias",
        related_metadata="OUM vouchers",
        in_app_via="",
        action="Prefer adding OUM alias (see P3) rather than relying on OUMNH.",
    ),
]


def main() -> None:
    fields = [
        "priority",
        "impact",
        "prefix",
        "species_count",
        "suggested_full_name",
        "city_country",
        "fix_type",
        "related_metadata",
        "in_app_via",
        "action",
    ]
    with OUT.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fields)
        writer.writeheader()
        writer.writerows(ROWS)
    p1 = sum(r["species_count"] for r in ROWS if r["priority"] == 1 and r["impact"] != "needs_review")
    p2 = sum(r["species_count"] for r in ROWS if r["priority"] == 2)
    p3 = sum(r["species_count"] for r in ROWS if r["priority"] == 3)
    print(f"Wrote {OUT}")
    print(f"P1 quick wins (excl. MN review): {p1} species")
    print(f"P2 medium: {p2} species")
    print(f"P3 hidden aliases (already on map via other code): {p3} species")


if __name__ == "__main__":
    main()
